title: Anna Gujgiczer
description: |-
PhD student at Budapest University of Technology and Economics
Faculty of Electrical Engineering and Informatics
Department of Computer Science and Information Theory
theme: minima
#remote_theme: pages-themes/tactile@v0.2.0
#plugins:
#- jekyll-remote-theme
