title: Anna Gujgiczer
author: Anna Gujgiczer

description: |
  Budapest University of Technology and Economics
  Faculty of Electrical Engineering and Informatics
  Department of Computer Science and Information Theory
  
email: gujgicza@cs.bme.hu
  
theme: minima

header_pages:
  - about.md
  - publications.md
  - talks.md

include:
  - publications.md
  - talks.md
  
exclude:
  - README.md
